import os
import textwrap
from datetime import datetime
from typing import Optional

from docx import Document
from docx.shared import Inches, Pt
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

from app.config import settings


REPORT_DIR = "generated_reports"

PAGE_WIDTH, PAGE_HEIGHT = A4
LEFT_MARGIN = 45
RIGHT_MARGIN = 45
BOTTOM_CONTENT_Y = 78
FOOTER_Y = 24


def ensure_report_dir():
    os.makedirs(REPORT_DIR, exist_ok=True)


def safe_filename(name: str) -> str:
    cleaned = "".join(ch for ch in name if ch.isalnum() or ch in ("_", "-"))
    return cleaned or "patient"


def format_status(status: str) -> str:
    value = (status or "").lower()

    if "doctor" in value and "approved" in value:
        return "Doctor Approved Prescription"

    if "draft" in value or "ai" in value:
        return "AI Prescription Draft"

    return "Prescription"


def is_numbered_line(line: str) -> bool:
    parts = line.split(".", 1)
    return len(parts) == 2 and parts[0].strip().isdigit()


def draw_footer(c: canvas.Canvas):
    c.setFont("Helvetica", 6)
    c.setFillColor(colors.HexColor("#9ca3af"))
    c.drawRightString(
        PAGE_WIDTH - RIGHT_MARGIN,
        FOOTER_Y,
        "Generated by MediGuard AI | Powered by Groq AI + Smart Clinical Automation",
    )


def draw_header(c: canvas.Canvas, consultation_id: int, status_label: str):
    width, height = A4

    c.setFillColor(colors.HexColor("#0f172a"))
    c.rect(0, height - 100, width, 100, stroke=0, fill=1)

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(LEFT_MARGIN, height - 38, settings.APP_NAME)

    c.setFont("Helvetica", 9)
    c.drawString(
        LEFT_MARGIN,
        height - 58,
        "Powered by Groq AI + Smart Clinical Automation",
    )

    c.setFont("Helvetica-Bold", 10)
    c.drawRightString(width - RIGHT_MARGIN, height - 38, status_label)

    c.setFont("Helvetica", 8)
    c.drawRightString(
        width - RIGHT_MARGIN,
        height - 58,
        f"Prescription ID: RX-{consultation_id:04d}",
    )
    c.drawRightString(
        width - RIGHT_MARGIN,
        height - 74,
        f"Date: {datetime.now().strftime('%d %b %Y')}",
    )

    return height - 130


def new_pdf_page(c: canvas.Canvas, consultation_id: int, status_label: str):
    draw_footer(c)
    c.showPage()
    return draw_header(c, consultation_id, status_label)


def ensure_space(
    c: canvas.Canvas,
    y: int,
    required_height: int,
    consultation_id: int,
    status_label: str,
):
    if y - required_height < BOTTOM_CONTENT_Y:
        return new_pdf_page(c, consultation_id, status_label)

    return y


def draw_status_card(
    c: canvas.Canvas,
    x: int,
    y: int,
    consultation_id: int,
    status_label: str,
):
    y = ensure_space(c, y, 45, consultation_id, status_label)

    if "Draft" in status_label:
        bg = "#e0f2fe"
        fg = "#075985"
        text = "AI Prescription Draft - Waiting for Doctor Review"
    else:
        bg = "#dcfce7"
        fg = "#166534"
        text = "Doctor Approved Prescription"

    c.setFillColor(colors.HexColor(bg))
    c.roundRect(x, y - 32, PAGE_WIDTH - 90, 32, 8, stroke=0, fill=1)

    c.setFillColor(colors.HexColor(fg))
    c.setFont("Helvetica-Bold", 10)
    c.drawString(x + 12, y - 21, text)

    return y - 55


def draw_section_title(
    c: canvas.Canvas,
    title: str,
    x: int,
    y: int,
    consultation_id: int,
    status_label: str,
):
    y = ensure_space(c, y, 42, consultation_id, status_label)

    c.setFillColor(colors.HexColor("#111827"))
    c.setFont("Helvetica-Bold", 12)
    c.drawString(x, y, title)

    y -= 8
    c.setStrokeColor(colors.HexColor("#d1d5db"))
    c.line(x, y, PAGE_WIDTH - RIGHT_MARGIN, y)

    return y - 16


def draw_text(
    c: canvas.Canvas,
    text: str,
    x: int,
    y: int,
    consultation_id: int,
    status_label: str,
    bold: bool = False,
    size: int = 10,
    indent: int = 0,
    line_height: int = 14,
):
    font = "Helvetica-Bold" if bold else "Helvetica"
    max_chars = max(35, 92 - int(indent / 4))

    wrapped = textwrap.wrap(text, width=max_chars) or [""]

    for line in wrapped:
        y = ensure_space(c, y, line_height + 4, consultation_id, status_label)

        c.setFont(font, size)
        c.setFillColor(colors.HexColor("#111827"))
        c.drawString(x + indent, y, line)

        y -= line_height

    return y


def draw_emergency_warning(
    c: canvas.Canvas,
    x: int,
    y: int,
    consultation_id: int,
    status_label: str,
):
    y = ensure_space(c, y, 55, consultation_id, status_label)

    c.setFillColor(colors.HexColor("#fee2e2"))
    c.roundRect(x, y - 36, PAGE_WIDTH - 90, 36, 8, stroke=0, fill=1)

    c.setFillColor(colors.HexColor("#991b1b"))
    c.setFont("Helvetica-Bold", 11)
    c.drawString(
        x + 12,
        y - 23,
        "URGENT: Please seek emergency medical care immediately.",
    )

    return y - 55


def draw_generated_by_block(
    c: canvas.Canvas,
    x: int,
    y: int,
    consultation_id: int,
    status_label: str,
):
    y = ensure_space(c, y, 130, consultation_id, status_label)

    c.setStrokeColor(colors.HexColor("#d1d5db"))
    c.line(x, y, PAGE_WIDTH - RIGHT_MARGIN, y)

    y -= 28

    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#111827"))
    c.drawString(x, y, "Generated By")

    y -= 30

    c.setFont("Helvetica-Bold", 14)
    c.drawString(x, y, settings.APP_NAME)

    y -= 16

    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#374151"))
    c.drawString(x, y, "Powered by Groq AI + Smart Clinical Automation")

    return y - 20


def draw_doctor_signature_block(
    c: canvas.Canvas,
    x: int,
    y: int,
    consultation_id: int,
    status_label: str,
    doctor_name: str,
    doctor_registration: Optional[str],
    doctor_notes: Optional[str],
):
    y = ensure_space(c, y, 210, consultation_id, status_label)

    c.setStrokeColor(colors.HexColor("#d1d5db"))
    c.line(x, y, PAGE_WIDTH - RIGHT_MARGIN, y)

    y -= 28

    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#111827"))
    c.drawString(x, y, "Doctor Signature")

    y -= 40

    c.setFont("Helvetica-Oblique", 20)
    c.drawString(x, y, doctor_name)

    y -= 10

    c.setStrokeColor(colors.HexColor("#111827"))
    c.line(x, y, x + 230, y)

    y -= 20

    c.setFont("Helvetica-Bold", 10)
    c.drawString(x, y, doctor_name)

    y -= 15

    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#374151"))
    c.drawString(x, y, f"Registration No: {doctor_registration or ''}")

    if doctor_notes:
        y -= 22

        c.setFont("Helvetica-Bold", 9)
        c.setFillColor(colors.HexColor("#111827"))
        c.drawString(x, y, "Doctor Notes:")

        y -= 13

        y = draw_text(
            c,
            doctor_notes,
            x,
            y,
            consultation_id,
            status_label,
            bold=False,
            size=9,
            indent=0,
            line_height=13,
        )

    return y


def create_pdf(
    consultation_id: int,
    patient_name: str,
    prescription_text: str,
    status: str,
    doctor_name: Optional[str] = None,
    doctor_registration: Optional[str] = None,
    doctor_notes: Optional[str] = None,
) -> str:
    ensure_report_dir()

    status_label = format_status(status)
    filename = f"consultation_{consultation_id}_{safe_filename(patient_name)}_{status}.pdf"
    path = os.path.join(REPORT_DIR, filename)

    c = canvas.Canvas(path, pagesize=A4)

    x = LEFT_MARGIN
    y = draw_header(c, consultation_id, status_label)
    y = draw_status_card(c, x, y, consultation_id, status_label)

    headings = [
        "patient details:",
        "patient information:",
        "chief complaints:",
        "provisional diagnosis:",
        "possible diagnosis:",
        "rx:",
        "advice:",
        "healthcare advice:",
        "investigations:",
        "investigation advice:",
        "follow-up:",
        "follow-up advice:",
    ]

    for raw_line in prescription_text.splitlines():
        line = raw_line.strip()

        if not line:
            y -= 8
            continue

        lower = line.lower()

        if "please seek emergency medical care immediately" in lower:
            y = draw_emergency_warning(c, x, y, consultation_id, status_label)
            continue

        if lower in headings:
            title = line.replace(":", "")
            if title.lower() == "rx":
                title = "Rx"
            y = draw_section_title(c, title, x, y, consultation_id, status_label)
            continue

        if line.startswith("-"):
            y = draw_text(
                c,
                f"• {line[1:].strip()}",
                x,
                y,
                consultation_id,
                status_label,
                bold=False,
                size=10,
                indent=12,
                line_height=14,
            )
            continue

        if is_numbered_line(line):
            y = draw_text(
                c,
                line,
                x,
                y,
                consultation_id,
                status_label,
                bold=True,
                size=10,
                indent=0,
                line_height=15,
            )
            continue

        if lower.startswith(("dose:", "frequency:", "duration:", "note:")):
            y = draw_text(
                c,
                line,
                x,
                y,
                consultation_id,
                status_label,
                bold=False,
                size=9,
                indent=22,
                line_height=13,
            )
            continue

        y = draw_text(
            c,
            line,
            x,
            y,
            consultation_id,
            status_label,
            bold=False,
            size=10,
            indent=0,
            line_height=14,
        )

    y -= 20

    if doctor_name:
        draw_doctor_signature_block(
            c,
            x,
            y,
            consultation_id,
            status_label,
            doctor_name,
            doctor_registration,
            doctor_notes,
        )
    else:
        draw_generated_by_block(c, x, y, consultation_id, status_label)

    draw_footer(c)
    c.save()

    return path


def setup_docx_styles(doc: Document):
    section = doc.sections[0]

    section.top_margin = Inches(0.55)
    section.bottom_margin = Inches(0.55)
    section.left_margin = Inches(0.65)
    section.right_margin = Inches(0.65)

    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(10.5)


def create_docx(
    consultation_id: int,
    patient_name: str,
    prescription_text: str,
    status: str,
    doctor_name: Optional[str] = None,
    doctor_registration: Optional[str] = None,
    doctor_notes: Optional[str] = None,
) -> str:
    ensure_report_dir()

    status_label = format_status(status)
    filename = f"consultation_{consultation_id}_{safe_filename(patient_name)}_{status}.docx"
    path = os.path.join(REPORT_DIR, filename)

    doc = Document()
    setup_docx_styles(doc)

    title = doc.add_paragraph()
    title_run = title.add_run(settings.APP_NAME)
    title_run.bold = True
    title_run.font.size = Pt(20)

    subtitle = doc.add_paragraph()
    subtitle_run = subtitle.add_run("Powered by Groq AI + Smart Clinical Automation")
    subtitle_run.font.size = Pt(9)

    status_p = doc.add_paragraph()
    status_run = status_p.add_run(status_label)
    status_run.bold = True

    doc.add_paragraph(f"Prescription ID: RX-{consultation_id:04d}")
    doc.add_paragraph(f"Date: {datetime.now().strftime('%d %b %Y')}")

    headings = [
        "patient details:",
        "patient information:",
        "chief complaints:",
        "provisional diagnosis:",
        "possible diagnosis:",
        "rx:",
        "advice:",
        "healthcare advice:",
        "investigations:",
        "investigation advice:",
        "follow-up:",
        "follow-up advice:",
    ]

    for raw_line in prescription_text.splitlines():
        line = raw_line.strip()

        if not line:
            doc.add_paragraph("")
            continue

        lower = line.lower()

        if "please seek emergency medical care immediately" in lower:
            p = doc.add_paragraph()
            r = p.add_run("URGENT: Please seek emergency medical care immediately.")
            r.bold = True

        elif lower in headings:
            doc.add_heading(line.replace(":", ""), level=2)

        elif line.startswith("-"):
            doc.add_paragraph(line[1:].strip(), style="List Bullet")

        elif is_numbered_line(line):
            p = doc.add_paragraph()
            r = p.add_run(line)
            r.bold = True

        else:
            doc.add_paragraph(line)

    if doctor_name:
        doc.add_heading("Doctor Signature", level=2)

        p = doc.add_paragraph()
        r = p.add_run(doctor_name)
        r.italic = True
        r.font.size = Pt(18)

        doc.add_paragraph("____________________________")
        doc.add_paragraph(doctor_name)
        doc.add_paragraph(f"Registration No: {doctor_registration or ''}")

        if doctor_notes:
            note_title = doc.add_paragraph()
            note_run = note_title.add_run("Doctor Notes:")
            note_run.bold = True

            doc.add_paragraph(doctor_notes)

    else:
        doc.add_heading("Generated By", level=2)
        doc.add_paragraph(settings.APP_NAME)
        doc.add_paragraph("Powered by Groq AI + Smart Clinical Automation")

    footer = doc.add_paragraph()
    footer_run = footer.add_run(
        "Generated by MediGuard AI | Powered by Groq AI + Smart Clinical Automation"
    )
    footer_run.font.size = Pt(8)

    doc.save(path)

    return path